title: Pham Manh Tuyen
logo: /assets/img/Pic-person-05.jpg
email: tuyenmpham92@gmail.com
twitter: TuyenPh57861691
description: Your Friendly Neighborhood Cosmologist
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  
platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/tuyenmpham
  - name: ORCID
    icon: <i class="fa-brands fa-orcid"></i>
    link: https://orcid.org/0009-0002-5974-4082
  - name: iNSPIRE-HEP
    icon: <img src="https://inspirehep.net/favicon.ico" alt="InspireHEP Icon" width="16" height="16">
    link: https://inspirehep.net/authors/1882869?ui-citation-summary=true
navigation:
  - name: Home
    link: ./index.html
  - name: Research
    link: ./research.html
    sublist:
      - name: Research Statement
        link: ./research.html#research-statement
      - name: Experience
        link: ./research.html#experience
      - name: My Curriculum Vitae
        link: ./TuyenMPham_CV.pdf
  - name: Bio
    link: ./bio.html
  - name: Contact
    link: ./contact.html
