title: Reggie Bernardo
logo: /assets/img/rcb.jpeg
email: reginaldchristianbernardo@gmail.com
twitter: reggiebernardo_
description: Your Friendly Neighborhood Cosmologist
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  
platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/reggiebernardo
  - name: Scholar
    icon: <i class="fa-brands fa-google"></i>
    link: https://scholar.google.com/citations?user=qoDKcvQAAAAJ&hl=en
  - name: ORCID
    icon: <i class="fa-brands fa-orcid"></i>
    link: https://orcid.org/0000-0001-8589-6851
  - name: iNSPIRE-HEP
    icon: <img src="https://inspirehep.net/favicon.ico" alt="InspireHEP Icon" width="16" height="16">
    link: https://inspirehep.net/authors/1758391
  - name: ResearchGate
    icon: <i class="fa-brands fa-researchgate"></i>
    link: https://www.researchgate.net/profile/Reginald-Christian-Bernardo

navigation:
  - name: Home
    link: ./index.html
  - name: Research
    link: ./research.html
    sublist:
      - name: Highlights
        link: ./research.html#highlights
      - name: Statement
        link: ./research.html#research-statement
      - name: Experience
        link: ./research.html#experience
      - name: My CV
        link: ./mycv.pdf
  - name: Teaching
    link: ./teaching.html
  - name: Bio
    link: ./bio.html
  - name: Contact
    link: ./contact.html